### ISSUE TITLE
Get template from a folder of `md` files

### ISSUE THREAD

**Issue by tsanyqudsi** [scaffdog/scaffdog#1072]
I've been wondering if scaffdog has the ability to input multiple files of markdown and merge them before creating a scaffold. It would be nice if I can separate the files from the `.config/app.md` to `.config/app/index.md` as the main file and spread the files inside the folder with multiple folders/directory.

The use case is for generating new apps (such as custom vite app) for a certain projects in a monorepo. Currently as I assume, the whole config has to be inside a single file and it would be a long file if I want to scaffold a vite project.

Other than that, it's a huge help for a lazy devs like me.

**Comment by wadackel** [comment]
Hi @tsanyqudsi, thank you for interesting scaffdog :dog:

Templating divided into multiple files is supported by the [read helper function](https://scaff.dog/docs/templates/helpers#read).

There were some very nice examples of real world projects using scaffdog, so those may be helpful.

> https://github.com/secretlint/secretlint/blob/7d8eda7018e1a4d1de605f36a1f664a9f74cf8de/.scaffdog/new-rule.md?plain=1#L12-L16

**Comment by tsanyqudsi** [comment]
@wadackel thanks man.. will try it, I'll close it then.
