### ISSUE TITLE
Getting templates from url

### ISSUE THREAD

**Issue by tsanyqudsi** [scaffdog/scaffdog#1265]
As for now  `scaffdog` only get files / templates from `.scaffdog` folder. Is there a way that we can get from an outside url ?

## Expected Behavior

I can set up a github repo that contains all the templates I need for my team's development. And scaffdog can get the templates from there.

## Reasoning

`scaffdog` is a seems like a simple tool but with overpowered potential. The only drawback I see (for now) `scaffdog` is project based. Means that it can only get templates from a single project.

While I can copy and paste the templates from other projects, for a freelancer like me that sometimes have functions and /or templates that I use in project A but not B and C.. and after few months I do project D and completely forgot that i made the templates in project A until mid-project.

I am open to help do a PR, however I am not a good Typescript dev compared to you.

**Comment by wadackel** [comment]
Hi @tsanyqudsi , thank you for using scaffdog :dog:

> As for now scaffdog only get files / templates from .scaffdog folder. Is there a way that we can get from an outside url ?

Currently, remote files are not supported. However, we plan to support them in the future.

If you need to use the same template across multiple repositories immediately, consider using a tool like [files-sync-action](https://github.com/wadackel/files-sync-action) to synchronize the files themselves :+1:

**Comment by tsanyqudsi** [comment]
Thank you for the comments. I will find a way to work around this issue then.
