### ISSUE TITLE
I want to solve "SyntaxError: Missing "}}".

### ISSUE THREAD

**Issue by deg84** [scaffdog/scaffdog#726]
I tried to generate a component file using the following code and got a `SyntaxError: Missing "}}"` error.

```tsx
import { {{ inputs.name | pascal }} as {{ inputs.name | pascal }}OG } from "react-native";
import { StyledComponent } from "nativewind";

import { useTheme } from "@acme/theme";

export type {{ inputs.name | pascal }}Props = React.ComponentPropsWithoutRef<typeof {{ inputs.name | pascal }}OG>;

export function {{ inputs.name | pascal }}(props: {{ inputs.name | pascal }}Props) {
  const theme = useTheme();

  return (
    <StyledComponent
      component={{{ inputs.name | pascal }}OG}
      {...props}
      style={[props.style, { backgroundColor: theme.colorTheme.primary }]}
    />
  );
}
```

The `component={{{ inputs.name | pascal }}OG}` in the code is the problem area.

For example, if the component name is `Text`, I want it to be `component={TextOG}`.

How do I change it to achieve this?

## Your Environment

- OS: macOS Ventura 13.3.1
- scaffdog version: 2.5.0

**Comment by wadackel** [comment]
Hi @deg84, Thank you for using scaffdog :dog:

There are two possible solutions to your issue :point_down:

## Pattern 1

First, consider calculating the delimiter string as a string.

```typescript
return (
  <StyledComponent
    component={{ "{" + (inputs.name | pascal) + "OG}" }}
    {...props}
    style={[props.style, { backgroundColor: theme.colorTheme.primary }]}
  />
);
```

In this pattern, we are using the [Grouping Operator](https://scaff.dog/docs/templates/template-engine#grouping-operator) to group the results of the pipe calculation and combine them with the delimiter string.

## Pattern 2

This is a slightly tricky method.

```typescript
return (
  <StyledComponent
    component={ {{- inputs.name | pascal -}} OG}
    {...props}
    style={[props.style, { backgroundColor: theme.colorTheme.primary }]}
  />
);
```

In this pattern, to clarify the boundaries of the delimiter string, we insert a space in the JSX Expression.
Moreover, by using [Whitespace Control](https://scaff.dog/docs/templates/template-engine#whitespace-control) to fill in the spaces before and after, you can get the output you want.

**Comment by deg84** [comment]
@wadackel Thank you for your response.

I apologize for overlooking the Grouping Operator. I also appreciate your helpful example regarding Whitespace Control. It's a bit complex, yet I find it enhances readability.

I value the time and advice you've offered. I plan to continue using Scaffdog. Thank you again.
