### ISSUE TITLE
`safe-eval` Vulnerability Issues

### ISSUE THREAD

**Issue by otofu-square** [scaffdog/scaffdog#766]
Thanks for the awesome library!

Now, we have a issue with the `safe-eval` library. It's got some unpatched security issues for about 4 years and Dependabot keeps flagging about 10 alerts because of it.
https://security.snyk.io/vuln/?search=safe-eval

Here are a couple of solutions I thought about:

1. Replace the current implementation with a custom one, leveraging Node.js's `vm`.
2. We could also consider Shadow Realms. It's still in ECMAScript Stage 3 and not completely stable, but there's a polyfill https://github.com/ambit-tsai/shadowrealm-api we can use.

Would love to know what you think. And if we decide on a path, I'm ready to help get it done 🙌

**Comment by otofu-square** [comment]
> Dependabot keeps flagging about 10 alerts because of it.

<img width="1333" alt="image" src="https://github.com/scaffdog/scaffdog/assets/10118235/921cc809-e39a-4b78-b156-c78c8273ec3a">

**Comment by wadackel** [comment]
Hi @otofu-square 

Removed `safe-eval` from dependencies! Already supported in `v2.5.1` :tada:

If you continue to have problems, please re-open the Issue.
