### ISSUE TITLE
How to generate README.md with codeblocks?

### ISSUE THREAD

**Issue by wickedest** [scaffdog/scaffdog#969]
Firstly, really nice job on scaffdog. I really like how you use the markdown scaffolding files. It is clever.
I have a question (maybe I'm doing something wrong). How do I scaffold a markdown file that has code backticks?

## Expected Behavior

I want to generate a markdown file with code examples (triple-backticks). Is there some way to escape the ``` such that the escapes are removed on generation? Unfortunately, I need to include images because, well, backticks.

## Actual Behavior

The README.md file gets truncated.

## Steps to Reproduce (including precondition)

{Please write here}

### Source
![image](https://github.com/scaffdog/scaffdog/assets/871639/f7663208-abd7-4d1f-9278-8d76dea678d3)

### Generated

![image](https://github.com/scaffdog/scaffdog/assets/871639/68c9dbab-66dc-4d05-bd97-5685310c7d9b)

## Your Environment

- OS: {Please write here}
- scaffdog version: {Please write here}

**Comment by wadackel** [comment]
Hi @wickedest, Thank you for using scaffdog :dog: :heart:

scaffdog uses GitHub flavored markdown. To view further code blocks within a code block, the following documentation may be helpful :point_down:

> To display triple backticks in a fenced code block, wrap them inside quadruple backticks.
> ````
> ```
> Look! You can see my backticks.
> ```
> ````
> **Document:**
> https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks

I have verified that the scaffdog playground produces the expected output :+1:

> **Playground:** (Please click the Generate button!)
> https://scaff.dog/playground?code=H4sIAAAAAAAAA1NWSAhydXTxddXLTUng4koAgtzEouyU%2FPI8LmWF6mqFzLyC0pJivbzE3FSF2louLmVlBc%2B84pLEnJzEksz8PLCWpMTiDC4VhYLMAqBysBwWnUB1YOO5AIzZB%2BtzAAAA&input=H4sIAAAAAAAAA4uuVspOrVSyUspLzE1V0lEqS8wpTQVyi5MT09JS8tOVamMBz%2B0iZCMAAAA%3D

**Comment by wickedest** [comment]
@wadackel , I somehow missed the four-backtick fence example. worked perfectly - tyvm, and keep up the good work!
